{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.webUI.name }}
            port:
              number: {{ .Values.webUI.service.port }}
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.userService.name }}
            port:
              number: {{ .Values.userService.service.port }}
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.productService.name }}
            port:
              number: {{ .Values.productService.service.port }}
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.orderService.name }}
            port:
              number: {{ .Values.orderService.service.port }}
{{- end }}