apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    name: ecommerce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: ecommerce
data:
  USER_SERVICE_URL: "http://user-service.ecommerce.svc.cluster.local:3001"
  PRODUCT_SERVICE_URL: "http://product-service.ecommerce.svc.cluster.local:3002"
  ORDER_SERVICE_URL: "http://order-service.ecommerce.svc.cluster.local:3003"